services:
  db-mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  be-nest:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      - PORT=8080
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      # - DB_HOST=host.docker.internal
    expose:
      - 8080
    ports:
      - 8080:8080

volumes:
  mongodb:
